remote_theme: zig-by-example/just-the-docs
logo: /assets/logo.png
title: Zig By Example
description: Learn How to use Zig's Standard Library, by simple and small examples.
color_scheme: zig
search_enabled: false

permalink: pretty
exclude: ["template/", ".vscode/", "README.md"]
